version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.31
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-247-85-251.eu-west-1.compute.amazonaws.com
            database: d7ertivhrd0aef
            schema: public
            user: sthajffypnbgrc
            password: 3c0461df9befa58e15e68f0694cea0838ec169c066d86792b55f5decea7b14be
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true